
server:
  port: 8765
spring:
  application:
    name: wine-provider-wy
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.123:3306/project?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    data-password: 123
    useSSL: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
mybatis:
  mapper-locations: mapper/*.xml
