server:
  port: 8764

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: springcloud-pre
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zs?serverTimezone=Hongkong
    username: root
    password: root

mybatis:
  mapper-locations: mapper/mapper*.xml
