server:
  port: 8764

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: springcloud-pre
  datasource:
    driverClassName: com.mysql.jdbc.Driver
<<<<<<< HEAD
    url: jdbc:mysql://192.168.1.10:3306/wineproject?serverTimezone=Hongkong
    username: root
    password: 123

mybatis:
  mapper-locations: mapper/mapper*.xml

=======
    url: jdbc:mysql://localhost:3306/zs?serverTimezone=Hongkong
    username: root
    password: root

mybatis:
  mapper-locations: mapper/mapper*.xml
>>>>>>> e2e918422d16336b0724d5db9e6013a108ab0a07
