server:
  port: 8767


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


spring:
  application:
    name: springcloud-order
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.10:3306/wineproject?serverTimezone=Hongkong
    username: root
    password: 123




mybatis:
  mapper-locations: mapper/*.xml
#  spring.datasource.driverClassName=com.mysql.jdbc.Driver
#  spring.datasource.url=jdbc:mysql://localhost:3306/1811?serverTimezone=Hongkong
#  spring.datasource.username=root
#  spring.datasource.password=123
#  mybatis.mapper-locations=mapper/*.xml
