server:
  port: 8092

spring:
  application:
    name: wine-consumer-seckillgoods-clq
  redis:
    host: 192.168.1.117
    database: 0
    port: 6379
    password: 123456
    timeout: 3000
    poolMaxTotal : 1000
    poolMaxIdle : 500
    poolMaxWait : 500
  resources:
    add-mappings: true
    chain:
      cache: true
      enabled: true
      html-application-cache: true
    static-locations: classpath:/static/
    cache:
      period: 3600
  thymeleaf:
    cache: true
    enabled: true
    encoding: UTF-8
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  main:
    allow-bean-definition-overriding: true
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


feign:
  hystrix:
    enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 300000